# Generated by Django 6.0.2 on 2026-06-03 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_alter_student_age_alter_student_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        18, message="Age kam az kam 18 saal honi chahiye!"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
