# Generated by Django 6.0.2 on 2026-06-03 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_alter_student_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        18, message="Age Must be at least 18"
                    ),
                    django.core.validators.MaxValueValidator(
                        90, message="Age must be less than 90"
                    ),
                ]
            ),
        ),
    ]
