# Generated by Django 6.0.2 on 2026-06-04 06:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0006_alter_student_age"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid phone number. It must contain digits only.",
                        regex="^\\d+$",
                    ),
                    django.core.validators.RegexValidator(
                        message="Invalid phone number. It must be exact 11 digits, numbers only, and start with 03 (e.g., 03001234567).",
                        regex="^.{11}$",
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="student.department",
            ),
        ),
    ]
