# Generated by Django 6.0.2 on 2026-06-04 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0007_department_alter_student_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="student.department",
            ),
        ),
    ]
