# Generated by Django 6.0.2 on 2026-06-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0008_alter_student_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="courses",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="student.course"
            ),
        ),
    ]
