# Generated by Django 6.0.2 on 2026-06-05 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0010_course_department"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="code",
            new_name="course_code",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="name",
            new_name="course_name",
        ),
        migrations.RenameField(
            model_name="department",
            old_name="code",
            new_name="dept_code",
        ),
        migrations.RenameField(
            model_name="department",
            old_name="name",
            new_name="dept_name",
        ),
    ]
