# Generated by Django 6.0.2 on 2026-06-05 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0011_rename_code_course_course_code_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="dept_code",
            new_name="department_code",
        ),
        migrations.RenameField(
            model_name="department",
            old_name="dept_name",
            new_name="department_name",
        ),
    ]
