# Generated by Django 6.0.2 on 2026-06-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0012_rename_dept_code_department_department_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_code",
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_name",
            field=models.CharField(max_length=100),
        ),
    ]
