# Generated by Django 6.0.2 on 2026-06-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0013_alter_course_course_code_alter_course_course_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="department",
        ),
        migrations.AddField(
            model_name="course",
            name="departments",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="student.department"
            ),
        ),
    ]
