# Generated by Django 6.0.2 on 2026-06-08 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0014_remove_course_department_course_departments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_code",
            field=models.CharField(
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid Code! Code must contain a mix of BOTH alphabets and numbers (e.g., CS101, MGT101), with no spaces or special characters.",
                        regex="^(?=.*[a-zA-Z])(?=.*[0-9])[a-zA-Z0-9]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid entry! Only alphabets and spaces are allowed.",
                        regex="^[a-zA-Z\\s]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="department_code",
            field=models.CharField(
                max_length=8,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid entry! Only alphabets and spaces are allowed.",
                        regex="^[a-zA-Z\\s]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="department_name",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid entry! Only alphabets and spaces are allowed.",
                        regex="^[a-zA-Z\\s]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid entry! Only alphabets and spaces are allowed.",
                        regex="^[a-zA-Z\\s]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid phone number. It must contain digits only.",
                        regex="^\\d+$",
                    ),
                    django.core.validators.RegexValidator(
                        message="Invalid phone number. It must be exactly 11 digits, start with 0, and contain only numbers.",
                        regex="^0\\d{9}$",
                    ),
                ],
            ),
        ),
    ]
