# Generated by Django 6.0.2 on 2026-06-09 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0015_alter_course_course_code_alter_course_course_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="department_code",
            field=models.CharField(
                max_length=8,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid Code! Code must contain a mix of BOTH alphabets and numbers (e.g., CS101, MGT101), with no spaces or special characters.",
                        regex="^(?=.*[a-zA-Z])(?=.*[0-9])[a-zA-Z0-9]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid phone number. It must contain digits only.",
                        regex="^\\d+$",
                    ),
                    django.core.validators.RegexValidator(
                        message="Invalid phone number! It must be exactly 11 digits long, start with '03', and contain numbers only.",
                        regex="^03\\d{9}$",
                    ),
                ],
            ),
        ),
    ]
