# Generated by Django 6.0.2 on 2026-06-09 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0016_alter_department_department_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="department_code",
            field=models.CharField(
                max_length=8,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid entry! Only alphabets and spaces are allowed.",
                        regex="^[a-zA-Z\\s]+$",
                    )
                ],
            ),
        ),
    ]
